"""Discovery field catalog aligned to APSA Client Discovery Document (CDD) V1."""

from __future__ import annotations

from typing import Any

FIELD_SECTIONS: list[dict[str, str]] = [
    {
        "id": "account",
        "title": "Account & business",
        "blurb": "Core company facts from the CDD Account / Business Information block.",
    },
    {
        "id": "audience",
        "title": "Audience & geography",
        "blurb": "Who you sell to and where.",
    },
    {
        "id": "commercial",
        "title": "Commercial metrics",
        "blurb": "Ticket size, LTV, lead modes — usually client-confirmed.",
    },
    {
        "id": "competitors",
        "title": "Competitors & strategy",
        "blurb": "Competitive set, SWOT, and strategic approach.",
    },
    {
        "id": "access",
        "title": "System access & credentials",
        "blurb": "CDD access checklist — Analytics, Ads, GTM, CMS, hosting, and access level.",
    },
    {
        "id": "brand",
        "title": "Brand, content & compliance",
        "blurb": "Guidelines, content notes, and claims you cannot make.",
    },
    {
        "id": "goals",
        "title": "Goals & promises",
        "blurb": "Business goals, SEO/SEM promises, and other marketing spend.",
    },
]

# D1 — can be drafted from public web / CDD upload research
RESEARCH_FIELDS = (
    "inferred_industry",
    "business_model",
    "business_keywords",
    "products",
    "products_for_promotion",
    "positioning",
    "geographic_focus",
    "target_demographic",
    "b2b_b2c",
    "industry_targeting",
    "competitors",
    "strengths",
    "weaknesses",
    "opportunities",
    "threats",
    "brand_guidelines",
    "public_reviews_summary",
    "social_presence",
    "google_business_signals",
)

# D2 — typically client / institutional knowledge
CLIENT_ONLY_FIELDS = (
    "business_goal",
    "average_ticket_size",
    "lifetime_value",
    "lead_modes",
    "strategy_approach",
    "sales_promises",
    "content_creation_notes",
    "blogs_notes",
    "revenue_split",
    "sales_cycle",
    "seasonality",
    "objectives",
    "other_marketing_spend",
    "seo_traffic_current",
    "seo_traffic_target",
    "sem_leads_current",
    "sem_leads_target",
    # CDD / onboarding access checklist (credentials & grant status)
    "analytics_access",
    "search_console_access",
    "gtm_access",
    "google_ads_access",
    "merchant_center_access",
    "cms_access",
    "hosting_access",
    "google_business_access",
    "access_level",
)

ACCESS_FIELDS = (
    "analytics_access",
    "search_console_access",
    "gtm_access",
    "google_ads_access",
    "merchant_center_access",
    "cms_access",
    "hosting_access",
    "google_business_access",
    "access_level",
)

DISCOVERY_FIELDS = [
    "inferred_industry",
    "business_model",
    "business_keywords",
    "products",
    "products_for_promotion",
    "geographic_focus",
    "target_demographic",
    "b2b_b2c",
    "competitors",
    "business_goal",
    "average_ticket_size",
    "lifetime_value",
    "lead_modes",
    "strengths",
    "weaknesses",
    "brand_guidelines",
    "sales_promises",
    "objectives",
    "analytics_access",
    "search_console_access",
    "gtm_access",
    "google_ads_access",
    "merchant_center_access",
    "cms_access",
    "hosting_access",
    "access_level",
]

OBJECTIVE_OPTIONS = [
    "Increase organic traffic",
    "Improve keyword rankings",
    "Improve conversion rate",
    "Generate more qualified leads",
    "Expand into new markets",
    "Reduce customer acquisition cost",
    "Strengthen brand authority",
    "Outrank specific competitors",
    "Support a product or service launch",
    "Grow paid search / SEM leads",
]

FIELD_META: dict[str, dict[str, Any]] = {
    "inferred_industry": {
        "section": "account",
        "label": "Industry",
        "help": "CDD: Industry",
        "input": "text",
    },
    "business_model": {
        "section": "account",
        "label": "Business model",
        "help": "Retail, Ecommerce, Trade, Professional Services, Manufacturing, Wholesale, etc.",
        "input": "textarea",
        "rows": 2,
    },
    "business_keywords": {
        "section": "account",
        "label": "Business keywords",
        "help": "Core service / product keyword themes.",
        "input": "textarea",
        "rows": 2,
    },
    "products": {
        "section": "account",
        "label": "Top services / profitable products",
        "help": "Top 3+ services or most profitable offerings.",
        "input": "textarea",
        "rows": 3,
    },
    "products_for_promotion": {
        "section": "account",
        "label": "Products / services for promotion",
        "help": "What SEO/SEM should push first.",
        "input": "textarea",
        "rows": 3,
    },
    "positioning": {
        "section": "account",
        "label": "Positioning",
        "help": "How the brand presents itself publicly.",
        "input": "textarea",
        "rows": 2,
    },
    "geographic_focus": {
        "section": "audience",
        "label": "Target geographic location",
        "help": "CDD: Targets Geographic Location",
        "input": "text",
    },
    "target_demographic": {
        "section": "audience",
        "label": "Targeted demographic",
        "help": "Age, income, lifestyle, core desires.",
        "input": "textarea",
        "rows": 3,
    },
    "b2b_b2c": {
        "section": "audience",
        "label": "B2B / B2C",
        "help": "Primary buyer type.",
        "input": "select",
        "options": ["B2C", "B2B", "Both"],
    },
    "industry_targeting": {
        "section": "audience",
        "label": "Industry targeting",
        "help": "Who within the industry you are targeting.",
        "input": "textarea",
        "rows": 2,
    },
    "average_ticket_size": {
        "section": "commercial",
        "label": "Average ticket size",
        "help": "CDD: Average Ticket Size",
        "input": "text",
        "client_only": True,
    },
    "lifetime_value": {
        "section": "commercial",
        "label": "Lifetime value (LTV)",
        "help": "CDD: Life Time Value",
        "input": "text",
        "client_only": True,
    },
    "lead_modes": {
        "section": "commercial",
        "label": "Main mode of lead",
        "help": "Call / web form / walk-in / ecommerce / referrals.",
        "input": "text",
        "client_only": True,
    },
    "revenue_split": {
        "section": "commercial",
        "label": "Revenue split",
        "help": "Online vs offline or by product line.",
        "input": "textarea",
        "rows": 2,
        "client_only": True,
    },
    "sales_cycle": {
        "section": "commercial",
        "label": "Sales cycle length",
        "input": "text",
        "client_only": True,
    },
    "seasonality": {
        "section": "commercial",
        "label": "Seasonality",
        "input": "textarea",
        "rows": 2,
        "client_only": True,
    },
    "seo_traffic_current": {
        "section": "commercial",
        "label": "SEO organic traffic (current)",
        "input": "text",
        "client_only": True,
    },
    "seo_traffic_target": {
        "section": "commercial",
        "label": "SEO organic traffic (target)",
        "input": "text",
        "client_only": True,
    },
    "sem_leads_current": {
        "section": "commercial",
        "label": "SEM / Ads leads (current)",
        "input": "text",
        "client_only": True,
    },
    "sem_leads_target": {
        "section": "commercial",
        "label": "SEM / Ads leads (target)",
        "input": "text",
        "client_only": True,
    },
    "competitors": {
        "section": "competitors",
        "label": "Competitors (min 3)",
        "help": "Names + URLs where possible.",
        "input": "textarea",
        "rows": 4,
    },
    "strategy_approach": {
        "section": "competitors",
        "label": "Strategy approach",
        "help": "Double down on strength vs make weakness a strength.",
        "input": "textarea",
        "rows": 2,
        "client_only": True,
    },
    "strengths": {
        "section": "competitors",
        "label": "SWOT — Strengths",
        "input": "textarea",
        "rows": 2,
    },
    "weaknesses": {
        "section": "competitors",
        "label": "SWOT — Weaknesses",
        "input": "textarea",
        "rows": 2,
    },
    "opportunities": {
        "section": "competitors",
        "label": "SWOT — Opportunities",
        "input": "textarea",
        "rows": 2,
    },
    "threats": {
        "section": "competitors",
        "label": "SWOT — Threats",
        "input": "textarea",
        "rows": 2,
    },
    "public_reviews_summary": {
        "section": "brand",
        "label": "Public reviews (summary)",
        "input": "textarea",
        "rows": 2,
    },
    "social_presence": {
        "section": "brand",
        "label": "Social presence",
        "input": "textarea",
        "rows": 2,
    },
    "google_business_signals": {
        "section": "brand",
        "label": "Google Business / local signals",
        "input": "textarea",
        "rows": 2,
    },
    "brand_guidelines": {
        "section": "brand",
        "label": "Brand guidelines / compliance",
        "help": "Tonality, audience, regulated claim words to avoid.",
        "input": "textarea",
        "rows": 3,
    },
    "content_creation_notes": {
        "section": "brand",
        "label": "Content creation notes",
        "input": "textarea",
        "rows": 2,
        "client_only": True,
    },
    "blogs_notes": {
        "section": "brand",
        "label": "Blogs / content plan notes",
        "input": "textarea",
        "rows": 2,
        "client_only": True,
    },
    "business_goal": {
        "section": "goals",
        "label": "Business goal",
        "help": "SEO / SEM goals from the CDD.",
        "input": "textarea",
        "rows": 2,
        "client_only": True,
    },
    "sales_promises": {
        "section": "goals",
        "label": "Sales promises",
        "help": "What was promised for SEO / Google Ads outcomes.",
        "input": "textarea",
        "rows": 2,
        "client_only": True,
    },
    "objectives": {
        "section": "goals",
        "label": "Objectives checklist",
        "help": "Select all that apply.",
        "input": "objectives",
        "client_only": True,
    },
    "other_marketing_spend": {
        "section": "goals",
        "label": "Other marketing spend (outside SEO)",
        "input": "textarea",
        "rows": 2,
        "client_only": True,
    },
    "analytics_access": {
        "section": "access",
        "label": "Analytics (GA4) access",
        "help": "CDD: Analytics Access — granted / pending / standard access / notes.",
        "input": "textarea",
        "rows": 2,
        "client_only": True,
    },
    "search_console_access": {
        "section": "access",
        "label": "Google Search Console access",
        "help": "Granted, pending, or who to invite.",
        "input": "textarea",
        "rows": 2,
        "client_only": True,
    },
    "gtm_access": {
        "section": "access",
        "label": "Google Tag Manager (GTM) access",
        "help": "CDD: GTM — pending / granted / container notes.",
        "input": "textarea",
        "rows": 2,
        "client_only": True,
    },
    "google_ads_access": {
        "section": "access",
        "label": "Google Ads access",
        "help": "CDD: Google Ad Access.",
        "input": "textarea",
        "rows": 2,
        "client_only": True,
    },
    "merchant_center_access": {
        "section": "access",
        "label": "Merchant Center access",
        "help": "CDD: Merchant Center (if ecommerce).",
        "input": "textarea",
        "rows": 2,
        "client_only": True,
    },
    "cms_access": {
        "section": "access",
        "label": "CMS / website admin access",
        "help": "WordPress, Shopify, Webflow, etc. — how we get in (no passwords in chat if possible).",
        "input": "textarea",
        "rows": 2,
        "client_only": True,
    },
    "hosting_access": {
        "section": "access",
        "label": "Hosting / DNS access",
        "help": "Hosting panel, DNS, CDN — who owns it and status.",
        "input": "textarea",
        "rows": 2,
        "client_only": True,
    },
    "google_business_access": {
        "section": "access",
        "label": "Google Business Profile access",
        "help": "GBP manager access status.",
        "input": "textarea",
        "rows": 2,
        "client_only": True,
    },
    "access_level": {
        "section": "access",
        "label": "Level of access",
        "help": "CDD: Level of Access — overall note on what is granted vs pending.",
        "input": "textarea",
        "rows": 2,
        "client_only": True,
    },
}

# Early intake on New Client form (non-personal business fields)
INTAKE_FORM_FIELDS = (
    "primary_contact_name",
    "primary_contact_email",
    "primary_contact_phone",
    "company_size",
    "headquarters_location",
    "target_audience",
    "geographic_focus",
    "known_competitors",
    "objectives",
    "website_priorities",
    "business_keywords",
    "b2b_b2c",
)

# Labels used when mapping CDD spreadsheet rows → keys
CDD_LABEL_ALIASES: dict[str, str] = {
    "business name": "business_name",
    "website url": "website_url",
    "account manager": "account_manager",
    "industry": "inferred_industry",
    "business model - retail,ecom,trade,proff services,mfg,wholesale etc": "business_model",
    "business model": "business_model",
    "business keywords": "business_keywords",
    "business goal": "business_goal",
    "what are your top 3 services/products or profitableservices/ products?": "products",
    "products /services list - for promotion": "products_for_promotion",
    "products / services list - for promotion": "products_for_promotion",
    "targets geographic location": "geographic_focus",
    "targeted demographic [age]": "target_demographic",
    "b2b/b2c": "b2b_b2c",
    "industry targeting": "industry_targeting",
    "average ticket size": "average_ticket_size",
    "life time value": "lifetime_value",
    "lifetime value": "lifetime_value",
    "main mode of lead - call/web form,walk in,ecom": "lead_modes",
    "main mode of lead": "lead_modes",
    "competitors [3 minimum]": "competitors",
    "competitors": "competitors",
    "strategy (double down on strength or make weakness a strength)": "strategy_approach",
    "strategy": "strategy_approach",
    "strengths": "strengths",
    "weaknesses": "weaknesses",
    "opportunities": "opportunities",
    "threats": "threats",
    "content creation": "content_creation_notes",
    "brand guidelines [tonality, audience, any other specific requirements]": "brand_guidelines",
    "brand guidelines": "brand_guidelines",
    "blogs": "blogs_notes",
    "sales promises": "sales_promises",
    # CDD Sheet2 — access / credentials
    "analytics access to? (standard access available)": "analytics_access",
    "analytics access to?": "analytics_access",
    "analytics access": "analytics_access",
    "merchant center access to? (if ecomm) (need to create one)": "merchant_center_access",
    "merchant center access to?": "merchant_center_access",
    "merchant center access": "merchant_center_access",
    "google ad access? (pending)": "google_ads_access",
    "google ad access?": "google_ads_access",
    "google ads access": "google_ads_access",
    "google ad access": "google_ads_access",
    "gtm? (pending)": "gtm_access",
    "gtm?": "gtm_access",
    "gtm": "gtm_access",
    "level of access? (pending)": "access_level",
    "level of access?": "access_level",
    "level of access": "access_level",
    "search console access": "search_console_access",
    "google search console": "search_console_access",
    "cms access": "cms_access",
    "cms / website admin": "cms_access",
    "hosting access": "hosting_access",
    "hosting / dns": "hosting_access",
    "google business profile": "google_business_access",
    "gbp access": "google_business_access",
}


def field_ui_meta() -> dict[str, Any]:
    return {
        "sections": FIELD_SECTIONS,
        "fields": FIELD_META,
        "objective_options": OBJECTIVE_OPTIONS,
    }


def cdd_json_schema_hint() -> str:
    """Compact key list for LLM prompts."""
    keys = list(RESEARCH_FIELDS) + list(CLIENT_ONLY_FIELDS)
    return ", ".join(keys)
